### PR TITLE
test: port to ModuleTestingEnvironment from HeadlessEnvironment

### LINKED ISSUE #63: replace HeadlessEnvironment tests with MTE
The tests that use HeadlessEnvironment are failing. (due to some changes made during the migration to gestalt-module v7)

Rather than fix HeadlessEnvironment, I recommend basing these tests on ModuleTestingEnvironment instead, so we don't have to maintain multiple testing-environment implementations.

### PR DESCRIPTION
**Pull request by keturn**
fixes #63

The easy cases look like this: [`fb53403`](https://github.com/Terasology/Pathfinding/pull/64/commits/fb5340342e21107c768d0c11f08c7a20f7b99979). Remove references to WorldProvidingHeadlessEnvironment, add the usual annotations for MTEExtension.

Tests also need to call `forceAndWaitForGeneration` before they place blocks; see https://github.com/Terasology/Pathfinding/pull/64#issuecomment-886228924

### CODE REVIEW

**Comment by keturn** [comment]
I've been working on HAStarTest, which is one of the ones using TextWorldBuilder.

It's getting null back from `chunk.getBlock(x, y, z)` during the `builder.parse` run. Not yet sure why. Looking at the `getBlock` implementation left me thinking that we need to make sure the **WalkableBlockFinderTest** is passing before working on any of the pathfinding tests using TextWorldBuilder.

**Comment by keturn** [comment]
I found a significant difference: https://github.com/MovingBlocks/Terasology/blob/e077b0de257cbf39f93b91ce684e43ca6dd3a7b2/engine-tests/src/main/java/org/terasology/engine/WorldProvidingHeadlessEnvironment.java#L27-L28
WorldProvidingHeadlessEnvironment provides a world based on `MapWorldProvider`, an in-memory implementation with much simpler chunk handling.

MTE uses the default world implementation, which has different features, like `setBlock` silently failing if the chunk isn't loaded. (Leading to methods like [forceAndWaitForGeneration](https://github.com/Terasology/ModuleTestingEnvironment/blob/7e90c2de1d3623d066ab9e3577d28f2e18925559/src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java#L231).)

On the one hand, I want to get this done without going down too many rabbit holes.

On the other hand, I really don't like `forceAndWaitForGeneration`, so it might be worth a look to see if we can change to using MapWorldProvider.

**Comment by keturn** [comment]
Unfortunately, it doesn't look easy to make the change to MapWorldProvider in MTE, so I left a note for later: https://github.com/Terasology/ModuleTestingEnvironment/issues/60

**Comment by keturn** [comment]
Not all the tests _pass,_ but they also don't _crash._ And all the MTE tests are appropriately tagged so their failures are recorded under "integration tests" instead of "unit tests."

File: src/test/java/org/terasology/pathfinding/PathfinderSystemTest.java [hunk 1]
```diff
@@ -53,9 +45,9 @@ public void updateChunkBeforePathRequests() throws InterruptedException {
         OnChunkLoaded chunkLoadedDummyEvent = new OnChunkLoaded(new Vector3i());
 
         navGraphSystem.chunkReady(chunkLoadedDummyEvent, entityRef);
-        ListenableFuture f1 = pathfinderSystem.requestPath(entityRef, new Vector3i(), Lists.newArrayList(new Vector3i()));
-        ListenableFuture f2 = pathfinderSystem.requestPath(entityRef, new Vector3i(), Lists.newArrayList(new Vector3i()));
-        ListenableFuture f3 = pathfinderSystem.requestPath(entityRef, new Vector3i(), Lists.newArrayList(new Vector3i()));
+        ListenableFuture<?> f1 = pathfinderSystem.requestPath(entityRef, new Vector3i(), Lists.newArrayList(new Vector3i()));
```
Comment (jdrueckert) [inline src/test/java/org/terasology/pathfinding/PathfinderSystemTest.java:48]: for my information: what does `<?>` do?

**Review by jdrueckert — APPROVED** [review]
The migration seems reasonable to me.

File: src/test/java/org/terasology/pathfinding/PathfinderSystemTest.java (hunk 1 above)
Comment (keturn) [reply src/test/java/org/terasology/pathfinding/PathfinderSystemTest.java:48]: The answer can be found here: _[What is the difference between the unbounded wildcard parameterized type and the raw type?](http://www.angelikalanger.com/GenericsFAQ/FAQSections/ParameterizedTypes.html#FAQ303)_

You may need to backtrack through some of the other linked entries there to get a hang of the jargon. Here, `ListenableFuture` was used as a _raw_ generic type, `ListenableFuture<List<Vector3i>>` would be a _parameterized_ type, and `ListenableFuture<?>` is a _wildcard_ parameterized type.

This changed motivated by the IntelliJ inspection "Raw use of parameterized class." The FAQ notes this enables the compiler to catch some cases that would have been warnings otherwise and reject them as errors.
